### ISSUE TITLE
Torrent - http

### ISSUE THREAD

**Issue by LIyoai** [DjazzLab/ocdownloader#11]
When I download a torrent file via http the torrent download will start directly in the background and stores it with wrong credentials (root:root) in the Downloads directory.
The torrent download is not displayed in ocdownloader, so i can't be paused or stopped by the user.

**Comment by DjazzLab** [comment]
The credential issue is just because the downloads folder has the wrong permissions (certainly due to application last updates)
You can either change the permissions directly on the server (via SSH) or remove the downloads folder and re-create it via the web interface. Then don't forget to set it in your personal settings.

**Comment by LIyoai** [comment]
Other files have correct credentials when I download.
Maybe it is not really clear.
I download debian-8.1.0-amd64-CD-1.iso.torrent via http. credentials are ok.
In background the torrent download is started automatically without any option to control.
and the downloaded iso has wrong credentials.

**Comment by DjazzLab** [comment]
Ho ok. If I understand well, this is an aria2c behavior, not an ocDownloader behavior.
This is why you don't have any control on the torrent download.

And the credential issue is due to the aria2c daemon user : root. All downloads that are not ordered by ocdownloader has the aria2c user:group permission. I don't know if the daemon could be run as www-data...

So the fix should be : don't authorize aria2c to start the torrent download automatically.

**Comment by LIyoai** [comment]
Not sure how to run aria2c as www-data because the user does not have a shell (security)

This should be the option:
--follow-torrent=true|false|mem

If true or mem is specified, when a file whose suffix is .torrent or content type is application/x-bittorrent is downloaded, aria2 parses it as a torrent file and downloads files mentioned in it. If mem is specified, a torrent file is not written to the disk, but is just kept in memory. If false is specified, the .torrent file is downloaded to the disk, but is not parsed as a torrent and its contents are not downloaded. Default: true

**Comment by DjazzLab** [comment]
Thanks !!!
I'll add this option in ocDownloader, tonight ;-)

**Comment by DjazzLab** [comment]
I've added this option to ocDownloader and this new feature will be available in the next update.
