### ISSUE TITLE
Cannot delete downloads from files

### ISSUE THREAD

**Issue by apg1980** [DjazzLab/ocdownloader#23]
I am using oc 8.0.5 and downloads are working properly.
after a download is finished i cannot delete them from files interface.
no garbage icon appears.
deleting from local (windows) let the windows downloader download it again.
is ocdownloader handling with wrong permissions from data directory of owncloud?

i can see my regulary permissions on the user dir is for deamon which the webserver are.
the downloads have owner and permissions for root.
this is with your documentation for the aria2 deamon.

**Comment by DjazzLab** [comment]
The aria2 daemon downloaded files get the user and group of the running daemon, which is root.
To prevent this, ocDownloader creates an empty file (with the PHP touch function, so the created file has your webserver user and group) in your ownCloud folder. Then aria2 download the content in that file. And because aria2 doesn't modify user and group of an existing file, the file is completely manageable from the interface.

But, there is some exceptions. For instance, if the download falls in error, the .aria2 security file is not removed. And this security file is created by aria2, so it's user and group are root:root and it's not removable via the ownCloud UI.

**Comment by apg1980** [comment]
so what can i do?

**Comment by DjazzLab** [comment]
The only thing you can do is to remove these files directly from the command line on your server.
And I will check if I can tell to ARIA2 to store the *.aria2 files in /tmp instead of the user folder so these files will not appears anymore in your ownCloud folder.

Just a question : Are you using the external storage application to use several local partitions on your server ?

**Comment by apg1980** [comment]
no i am not using external storage

**Comment by DjazzLab** [comment]
Ok, so you can delete these files using the server command line.
And I will change the way to save the current download session (in /tmp like the cURL download engine)

**Comment by apg1980** [comment]
hi any progress right here?

**Comment by DjazzLab** [comment]
Yep !
It's not possible to save *.aria2 control files (aria2c daemon control file) elsewhere than the current download folder.
As *.aria2 control files are automatically created by the daemon, the only way to allow the deletion of those files from the webUI is to run aria2c as www-data (web server user).

if aria2c daemon is run by the web server user, then *.aria2 control files are also created by the web server and have a "user:group" couple like "www-data:www-data".

I just find this solution and I'm writing a post on my wiki. I'll post the article URL right here in one hour (approximately).

**Comment by DjazzLab** [comment]
Here is how to run ARIA2C daemon as "www-data" : [OCDownloader:Run ARIA2C Daemon as www-data](https://wiki.sgc-univ.net/index.php/OCDownloader:Run_ARIA2C_Daemon_as_www-data)

Hope this helps !

**Comment by apg1980** [comment]
sorry i dont get it. my owncloud instance is running in a bitnami stack which is using daemon user to start the services. i tryed to adjust the passwd file like u descrived and tryed to start the aria2 daemon with no success. do you have any further instructions to get it run and also to make the steps not needet to take after each reboot again?
