### ISSUE TITLE
Not installable in ownClound App center

### ISSUE THREAD

**Issue by llaumgui** [DjazzLab/ocdownloader#31]
Hi,

ocDonwloader is visible from the app center but not installable because the link is not an archive. Is it possible to install ocDownloader from OC ?

**Comment by DjazzLab** [comment]
Hi !! Unfortunately not. Because I host the ocDownloader project on GitHub to make my life easier with application updates and versions.
So you should use one of the following methods to install the application :
- GIT command line : git clone <project git URL> (directly within the owncloud apps folder)
- Download the ZIP package from GitHub, unzip it in the owncloud apps folder and rename it (from "ocdownloader_master" to "ocdownloader")

Hope this helps

**Comment by llaumgui** [comment]
Thx for you response. You can also make a release and put a zip on this release to allow an easier installation ?

**Comment by DjazzLab** [comment]
On the ocDownloader GitHub main page, there is a button "Download ZIP" on the right side of your screen ;-)
