### ISSUE TITLE
Youtube video quality

### ISSUE THREAD

**Issue by omeunier** [DjazzLab/ocdownloader#5]
When downloading a youtube video, it's the second quality option that is automatically choosen.
Ex: when a video is available in 1080p, the 720p will be downloaded.

**Comment by DjazzLab** [comment]
Youtube-dl gets the best available video by default.
But if I add something to retrieve available formats, I think ocDownloader can control which format is downloaded.

Will try this tonight.

**Comment by DjazzLab** [comment]
The option **-f bestvideo** is now used in place of **-f best** when retrieving true youtube video URL.
I think **-f best** gives the best ration video/audio, so sometimes it's not the best quality available.

Now, the best video will always be preferred to the best ratio video/audio

**Comment by omeunier** [comment]
Now, I have the maximum quality.
But there is no soundtrack anymore in thedownloaded file

**Comment by DjazzLab** [comment]
Yep I noticed that.
All my tries with the **-f bestvideo** flag does not work and the video has no soundtrack.

But I found something !
Try to execute this command : /usr/local/bin/youtube-dl -F 'https://www.youtube.com/watch?v=cjGZltVZORA'
[youtube] cjGZltVZORA: Downloading webpage
[youtube] cjGZltVZORA: Extracting video information
[youtube] cjGZltVZORA: Downloading DASH manifest
[info] Available formats for cjGZltVZORA:
format code  extension  resolution note
171          webm       audio only DASH audio  120k , audio@128k (44100Hz), 1.95MiB
140          m4a        audio only DASH audio  129k , m4a_dash container, aac  @128k (44100Hz), 2.39MiB
141          m4a        audio only DASH audio  255k , m4a_dash container, aac  @256k (44100Hz), 4.75MiB
278          webm       256x144    DASH video   83k , webm container, VP9, 1fps, video only, 1.28MiB
160          mp4        256x144    DASH video  110k , 13fps, video only, 2.03MiB
242          webm       426x240    DASH video  159k , 1fps, video only, 2.59MiB
133          mp4        426x240    DASH video  249k , 25fps, video only, 4.56MiB
243          webm       640x360    DASH video  311k , 1fps, video only, 4.97MiB
134          mp4        640x360    DASH video  603k , 25fps, video only, 6.13MiB
244          webm       854x480    DASH video  640k , 1fps, video only, 9.28MiB
135          mp4        854x480    DASH video 1104k , 25fps, video only, 11.74MiB
247          webm       1280x720   DASH video 1393k , 1fps, video only, 18.36MiB
136          mp4        1280x720   DASH video 1947k , 25fps, video only, 21.49MiB
248          webm       1920x1080  DASH video 2292k , 1fps, video only, 30.21MiB
137          mp4        1920x1080  DASH video 3010k , 25fps, video only, 37.82MiB
17           3gp        176x144
36           3gp        320x240
5            flv        400x240
43           webm       640x360
18           mp4        640x360
22           mp4        1280x720   (best)

This command returns all available formats. The best video quality is 1080p, but it's a video only. So the default behavior of youtube-dl (choosing the best quality) will never return the 1080p with audio.

If you want the 1080p video with a soundtrack, you need to install [FFMPEG](https://wiki.sgc-univ.net/index.php/OCDownloader:Install_FFMpeg_(Debian_JESSIE)_to_Extract_Audio). But this is not supported by ocDownloader for now, because there is a post-processing operation (merge) after downloading both of the audio and the video.
