### ISSUE TITLE
Download folder for youtube video

### ISSUE THREAD

**Issue by omeunier** [DjazzLab/ocdownloader#6]
The permission on the download folder is root:root instead of www-data:www-data. Therefore, it's impossible for the user to remove a video.

**Comment by DjazzLab** [comment]
1. Could you try to completely remove the Downloads folder ? and recreate it using ownCloud ?
2. Do you use external storage for the Downloads folder ?
3. If yes, is the Downloads folder mounts a local path like /folder ?

Thanks ;-)

**Comment by omeunier** [comment]
1. I recreated the folder manually and it's now working fine :)
2. No, I don't

**Comment by DjazzLab** [comment]
I asked you these questions (2. and 3.) because if the mounted folder local path is /folder (and not /folder/files for example) then you'll never be able to have write permissions on that folder (even if the system user:group is www-data:www-data).

I've mounted an external local storage on another partition of my server. If the mounted folder is /folder then I can't remove anything in that folder via the OC user interface. So I create another local folder inside /folder (ex: /folder/files) and I mounted /folder/files in OC.
